### ISSUE TITLE
Errors updating wine-ge-custom

### ISSUE THREAD

**Issue by Mel34** [loathingKernel/PKGBUILDs#2]
Errors updating since https://github.com/loathingKernel/PKGBUILDs/commit/66aafa4f861c14f667c78c8c247fce830a9500ef
```
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing wine-ge-custom (1:GE.Proton8.10-3) breaks dependency 'wine' required by wine-mono
:: installing wine-ge-custom (1:GE.Proton8.10-3) breaks dependency 'wine' required by winetricks
```
Please clarify, does this mean wine is expected to be installed on the system alongside wine-ge-custom?

**Comment by loathingKernel** [comment]
`wine-ge-custom` no longer replaces `wine` or `wine-staging`. Because both `wine` and `wine-staging` conflict with any package providing the name `wine`, `wine-ge-custom` doesn't provide that any more. So in short, yes, `wine` or `wine-staging` will need to installed alongside `wine-ge-custom` to satisfy any packages requiring `wine` from now on.

**Comment by Mel34** [comment]
Thank you for clarification.

**Comment by grumpy-guy** [comment]
> So in short, yes, `wine` or `wine-staging` will need to installed alongside `wine-ge-custom` to satisfy any packages requiring `wine` from now on.

How do I do that? Trying to install `wine` or `wine-staging` results in:
`resolving dependencies...
looking for conflicting packages...
:: wine and wine-ge-custom are in conflict. Remove wine-ge-custom? [y/N]`

So, how I am supposed to get this working? I'm a bit lost here.

**Comment by loathingKernel** [comment]
you would need to remove wine-ge-custom, install wine-staging and then install wine-ge-custom again. But people have been raising some good point against this change in the AUR, so I am considering to revert it.

**Comment by grumpy-guy** [comment]
> you would need to remove wine-ge-custom, install wine-staging and then install wine-ge-custom again.

Ah, could have thought about that myself. Dammit.



> But people have been raising some good point against this change in the AUR, so I am considering to revert it.

Regardless of your decision, thank you for your work on this.

**Comment by Frederick888** [comment]
> so I am considering to revert it.

I'm also on the side of needing only one copy of Wine, but just throwing some ideas here: what about creating another package that depends on `wine-ge-custom` with `provides + conflicts=('wine')`, and it only installs a symlink?

**Comment by loathingKernel** [comment]
This is a really neat idea and I like it very much. A package that creates the expected executables in `/usr/bin`, installs a few other required files into `/usr` and depends on `wine-ge-custom`.

I just need a good suggestion on the naming of the interoperability package. Also, should the actual wine package retain the `wine-ge-custom` name or should `wine-ge-custom` refer to the interoperability package with depends on the package containing wine?

**Comment by Frederick888** [comment]
> I just need a good suggestion on the naming of the interoperability package.

Function-wise it's quite similar to https://aur.archlinux.org/packages/neovim-symlinks so we can probably call it `wine-ge-custom-symlinks`.

> Also, should the actual wine package retain the `wine-ge-custom` name or should `wine-ge-custom` refer to the interoperability package with depends on the package containing wine?

I guess turning `wine-ge-custom` into the symlink package can offer AUR helper users a smoother transition, but the package naming of both is gonna be much harder. So probably better to keep `wine-ge-custom` as it is but add the symlink one as an optional dependency.

**Comment by loathingKernel** [comment]
> I guess turning wine-ge-custom into the symlink package can offer AUR helper users a smoother transition, but the package naming of both is gonna be much harder. So probably better to keep wine-ge-custom as it is but add the symlink one as an optional dependency.

I can't think of a way it could fail if the proper package was renamed to `wine-ge-custom-base` or `wine-ge-custom-standalone` and the linkage package retained the `wine-ge-custom` name, as I am implementing this as a split package.

here is my proposed solution pending the final decision on how to handle the names https://github.com/loathingKernel/PKGBUILDs/commit/f23accf5da6ed51cc38e0ba1ceea6ff810577bf8

The package creates scripts such as the following
```sh
#!/usr/bin/sh
export PATH="/opt/wine-ge-custom/bin/:$PATH"
export LD_LIBRARY_PATH="/opt/wine-ge-custom/lib:/opt/wine-ge-custom/lib32:$LD_LIBRARY_PATH"
export WINEDLLPATH="/opt/wine-ge-custom/lib/wine:/opt/wine-ge-custom/lib32/wine:$WINEDLLPATH"
/opt/wine-ge-custom/bin/wine
```
instead of symlinks to point to the new install location.

**Comment by loathingKernel** [comment]
Let me post this here too.

> This is why we can't have nice things.
> 
>Ok, joking aside, I reverted everything back to normal and made `wine-ge-custom-opt` into its own thing. I am sorry for the inconvenience caused by these updates. In my defense, I had been sitting on these issues and solutions too long, unsure how to proceed because of lack of any feedback. Your feedback cleared a lot of things on how you are using this package and how it should be handled.
